export const ActionTypes = {
    SET_DEFAULT_MOVIES : 'SET_DEFAULT_MOVIES',
    SET_MOVIE_RESULT: 'SET_MOVIE_RESULT',
    SET_MOVIE_DETAIL_RESULT: 'SET_MOVIE_DETAIL_RESULT',

    SET_MODAL: 'SET_MODAL'
};